apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spapi
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: /internal/isalive
    initialDelay: 10
  readiness:
    path: /internal/isready
    initialDelay: 10
    periodSeconds: 1
  preStopHook:
    http:
      path: /internal/stop
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 400
  prometheus:
    enabled: true
    path: /internal/metrics
  maskinporten:
    enabled: true
    scopes:
      exposes:
        {{# each apis as |api| }}
        - name: "{{api.scope}}"
          enabled: true
          product: "sykepenger"
          consumers:
            {{# each api.consumers as |consumer| }}
            - name: "{{consumer.navn}}"
              orgno: "{{consumer.organisasjonsnummer}}"
            {{/each}}
        {{# if api.enableIntegratorer }}
        - name: "delegert{{api.scope}}"
          enabled: true
          product: "sykepenger"
          separator: "/"
          delegationSource: altinn
          consumers:
            {{# each api.integratorer as |integrator|}}
            - name: "{{integrator.navn}}"
              orgno: "{{integrator.organisasjonsnummer}}"
            {{/each}}
        {{/if}}
        {{/each}}
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
  accessPolicy:
    outbound:
      rules:
        - application: spokelse
      external:
        - host: {{pdlHost}}
  kafka:
    pool: {{kafkaPool}}
  secureLogs:
    enabled: true
  env:
    - name: AUDIENCE
      value: {{ingress}}
    - name: SPORINGSLOGG_TOPIC
      value: {{sporingsloggTopic}}
    - name: SPOKELSE_SCOPE
      value: {{spokelseScope}}
    - name: PDL_HOST
      value: {{pdlHost}}
    - name: PDL_SCOPE
      value: {{pdlScope}}
  observability:
    logging:
      destinations:
        - id: elastic
