apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spapi
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: /internal/isalive
    initialDelay: 5
  readiness:
    path: /internal/isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
    path: /internal/metrics
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "fellesordningenforafp.read"
          enabled: true
          product: "sykepenger"
          consumers:
            {{# each consumers as |consumer| }}
            - name: {{consumer.name}}
              orgno: {{consumer.orgno}}
            {{/each}}
  env:
    - name: AUDIENCE
      value: {{ingress}}