openapi: "3.0.0"
info:
  title: Spaπ (SP-API)
  description: |-
    Spaπ tilbyr Sykepengeinformasjon til eksterne konsumenter som har hjemmel til å hente det. 
    Konsumenter må logge seg inn med token fra Maskinporten med rett `audience` & `scope`.
    
    Alle oppslag spores, slik at personene det gjøres oppslag på vil kunne se at konsumenten har hentet sykepengeinformasjon om dem.
    
    Linker til autentisering
    - [Maskinporten](https://docs.digdir.no/docs/Maskinporten/)
    - [Audience restricted tokens](https://docs.digdir.no/docs/Maskinporten/maskinporten_func_audience_restricted_tokens)
    
    Audience:
    `https://spapi.ekstern.dev.nav.no`
    
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
  
  - url: https://spapi.ekstern.dev.nav.no
    description: Test
  - url: http://localhost:8080
    description: Lokalt
  
tags:

  - name: Fellesordningen for AFP
    description: orgnr. 987414502, 889640782

  - name: Avtalefestet pensjon
    description: orgnr. 982583462, 938708606, 982759412, 958995369, 931936492, 916833520, 940380014, 980650383, 889640782

paths:
  
    /fellesordningen-for-afp:
      post:
        summary: Hente utbetalte perioder
        tags:
          - Fellesordningen for AFP
        description: |-
          Hente utbetalte perioder for én person
          
          Utbetalte sykepengeperioder er eksklusiv arbeidsgiverperioden.
          
          Om den tilsluttede virksomheten har endret organisasjonsnummer innenfor tidsintervallet det etterspørres informasjon må det sendes en request per organisasjonsnummer.
          
          
          
          
          Scope: (én av):
          
          `nav:sykepenger:fellesordningenforafp.read`
          

        security:
          - maskinporten: []
        parameters:
          - in: header
            name: x-callid
            description: En UUID konsumenten sender inn som brukes til videre logging og feilsøking.
            schema:
              type: string
              format: uuid

        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestV1'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseV1'
          '400':
            description: Feil i request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Valderingsfeil'
          '401':
            description: Mangler access token
          '403':
            description: Feil scope/audience i token
          '429':
            description: For mange forespørsler på kort tid, prøv igjen om noen minutter
          '500':
            description: Feil på tjeneste, meld fra og send med feilreferanse
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UhaandtertFeil'
  
    /avtalefestet-pensjon:
      post:
        summary: Hente utbetalte perioder
        tags:
          - Avtalefestet pensjon
        description: |-
          Hente utbetalte perioder for én person
          
          Utbetalte sykepengeperioder er eksklusiv arbeidsgiverperioden.
          
          Om den tilsluttede virksomheten har endret organisasjonsnummer innenfor tidsintervallet det etterspørres informasjon må det sendes en request per organisasjonsnummer.
          
          
          Feltet `saksId` _må_ settes, med unntak for visse konsumenter;
          
          ✅ Statens pensjonskasse (982583462) - Vil bli påkrevd 1.Januar 2025.
          
          ✅ Storebrand pensjonstjenester (931936492) - Har integrert uten `saksId`, avventer bekreftelse på at de legger det ved.
          
          ✅ Kommunal landspensjonskasse (938708606) - Har integrert uten `saksId`, avventer bekreftelse på at de legger det ved.
          
          ❌ Øvrig konsumenter vil få en HTTP 400 om `saksId` mangler
          
          
          
          Scope: (én av):
          
          `nav:sykepenger:avtalefestetpensjon.read`
          
          `nav:sykepenger/delegertavtalefestetpensjon.read`
          

        security:
          - maskinporten: []
        parameters:
          - in: header
            name: x-callid
            description: En UUID konsumenten sender inn som brukes til videre logging og feilsøking.
            schema:
              type: string
              format: uuid

        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestV2'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseV2'
          '400':
            description: Feil i request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Valderingsfeil'
          '401':
            description: Mangler access token
          '403':
            description: Feil scope/audience i token
          '429':
            description: For mange forespørsler på kort tid, prøv igjen om noen minutter
          '500':
            description: Feil på tjeneste, meld fra og send med feilreferanse
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UhaandtertFeil'
  
components:
  schemas:
    RequestV1:
      type: object
      required: ["personidentifikator", "organisasjonsnummer", "fraOgMedDato", "tilOgMedDato"]
      properties:
        personidentifikator:
          type: string
          pattern: '^\d{11}$'
          description: Personidentifikator for personen
          example: 11111111111
        organisasjonsnummer:
          type: string
          pattern: '^\d{9}$'
          description: Organisasjonsnummer til underenheten som er tilsluttet ordningen
          example: 999999999
        fraOgMedDato:
          type: string
          format: date
          description: Fra og med dato
          example: 2021-01-01
        tilOgMedDato:
          type: string
          format: date
          description: Til og med dato
          example: 2021-01-31
        minimumSykdomsgrad:
          type: integer
          minimum: 1
          maximum: 100
          description: Anbefalt, men valgfri. Minimum sykdomsgrad som er aktuelt å utlevere informasjon om for å vurdere vilkårene for AFP for den aktuelle underenheten
          example: 80
    RequestV2:
      type: object
      required: ["personidentifikator", "organisasjonsnummer", "fraOgMedDato", "tilOgMedDato"]
      properties:
        personidentifikator:
          type: string
          pattern: '^\d{11}$'
          description: Personidentifikator for personen
          example: 11111111111
        organisasjonsnummer:
          type: string
          pattern: '^\d{9}$'
          description: Organisasjonsnummer til underenheten som er tilsluttet ordningen
          example: 999999999
        fraOgMedDato:
          type: string
          format: date
          description: Fra og med dato
          example: 2021-01-01
        tilOgMedDato:
          type: string
          format: date
          description: Til og med dato
          example: 2021-01-31
        minimumSykdomsgrad:
          type: integer
          minimum: 1
          maximum: 100
          description: Anbefalt, men valgfri. Minimum sykdomsgrad som er aktuelt å utlevere informasjon om for å vurdere vilkårene for AFP for den aktuelle underenheten
          example: 80
        saksId:
          type: string
          description: SaksId'en til konsumenten som den gjør oppslag for
          example: "086BE575-25E1-4425-8970-A16A9D7953E9"
    UtbetaltPeriodeV1:
      type: object
      required: ["fraOgMedDato", "tilOgMedDato", "tags"]
      properties:
        fraOgMedDato:
          type: string
          format: date
          description: Fra og med dato
          example: 2021-01-01
        tilOgMedDato:
          type: string
          format: date
          description: Til og med dato
          example: 2021-01-31
        sykdomsgrad:
          type: integer
          minimum: 1
          maximum: 100
          description: Utelates fra responsen om 'minimumSykdomsgrad' settes i requesten. Sykdomsgrad er graden som arbeidstaker har vært arbeidsufør for et arbeidsforhold i perioden – denne kan avvike fra sykmeldingsgraden i sykmeldingen
          example: 80
        tags:
          type: array
          description: Tags som gjelder perioden. Om perioden er markert med UsikkerSykdomsgrad betyr dette at den bør ettergås manuelt
          items:
            type: string
            enum:
              - UsikkerSykdomsgrad
    ResponseV1:
      type: object
      required: [ "utbetaltePerioder" ]
      properties:
        utbetaltePerioder:
          type: array
          description: Perioder med utbetaling
          items:
            $ref: '#/components/schemas/UtbetaltPeriodeV1'
    ResponseV2:
      type: object
      required: [ "utbetaltePerioder" ]
      properties:
        saksId:
          type: string
          description: SaksId'en som ble sendt inn i requesten (Kommer kun i responsen om den var sendt med i requesten)
          example: "086BE575-25E1-4425-8970-A16A9D7953E9"
        utbetaltePerioder:
          type: array
          description: Perioder med utbetaling
          items:
            $ref: '#/components/schemas/UtbetaltPeriodeV1'
    Valderingsfeil:
      type: object
      required: ["feilmelding", "feilreferanse"]
      properties:
        feilmelding:
          type: string
          description: Detaljert beskrivelse av feilen
          example: Ugyldig verdi i feltet ‘tilOgMedDato’ i request body. (var “29.09.1990”)
        feilreferanse:
          type: string
          format: uuid
          description: Id som identifiserer requesten
          example: fd209ea5-4b3e-4185-991a-918a944c1c18
    UhaandtertFeil:
      type: object
      required: ["feilmelding", "feilreferanse"]
      properties:
        feilmelding:
          type: string
          description: En ikke håndtert feilsituasjon har oppstått
          example: Uventet feil. Ta kontakt med NAV om feilen vedvarer.
        feilreferanse:
          type: string
          format: uuid
          description: Id som identifiserer requesten
          example: 6b120ff7-ea67-4d00-b2ea-ff054c6e4b43
  securitySchemes:
    maskinporten:
      type: http
      scheme: bearer
      bearerFormat: JWT