[versions]
tbdLibs = "20260702.1010"
sykepengerGradlePlugins = "20261001.1830"

[libraries]
handlebars = "com.github.jknack:handlebars:4.5.5"
jsonassert = "org.skyscreamer:jsonassert:1.5.3"

jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml" }

kafka-clients = "org.apache.kafka:kafka-clients:4.3.1"

ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger" }

logback-classic = "ch.qos.logback:logback-classic:1.6.3"
logstash-logback-encoder = "net.logstash.logback:logstash-logback-encoder:9.0"
slf4j-api = "org.slf4j:slf4j-api:2.0.20"

wiremock = "org.wiremock:wiremock-jetty12:3.13.2"

tbd-libs-azure-token-client-default = { module = "com.github.navikt.tbd-libs:azure-token-client-default", version.ref = "tbdLibs" }
tbd-libs-naisful-app = { module = "com.github.navikt.tbd-libs:naisful-app", version.ref = "tbdLibs" }
tbd-libs-naisful-test-app = { module = "com.github.navikt.tbd-libs:naisful-test-app", version.ref = "tbdLibs" }
tbd-libs-retry = { module = "com.github.navikt.tbd-libs:retry", version.ref = "tbdLibs" }
tbd-libs-signed-jwt-issuer-test = { module = "com.github.navikt.tbd-libs:signed-jwt-issuer-test", version.ref = "tbdLibs" }

[bundles]
ktor-client = [
    "ktor-client-cio"
]
ktor-server = [
    "ktor-server-auth-jwt",
    "ktor-server-rate-limit",
    "ktor-server-swagger"
]
logback = [
    "logback-classic",
    "logstash-logback-encoder",
    "slf4j-api"
]

[plugins]
sykepenger-deployable = { id = "no.nav.sykepenger.deployable", version.ref = "sykepengerGradlePlugins" }
